[[redirects]]
  from = "/transfermarkt/*"
  to = "https://transfermarkt-api-psi.vercel.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  functions = "netlify/functions"
