[[redirects]]
  from = "/fotmob*"
  to = "https://www.fotmob.com/api/search/searchData?term=:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/transfermarkt/*"
  to = "https://transfermarkt-api-psi.vercel.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


